#!/bin/bash

# If being called from a systemd service, the first argument should be the action.
# Otherwise, we can try to infer it.
action=${1:-start}

for consumerpath in $TIPPR_CONSUMER_CONFIG/*; do
    consumer=$(basename $consumerpath)

    # allow targeting which consumer the event is meant for (defaulting to 'all')
    if [ ! -z "$TARGET" -a "x$TARGET" != "xall" -a "x$TARGET" != "x$consumer" ]; then
        continue
    fi

    if [ -d $consumerpath ]; then
        types=$consumerpath/*
    else
        types=$consumerpath
    fi

    for typepath in $types; do
        instance_count=$(cat $typepath)
        type_=$(basename $typepath)

        for i in $(seq 1 "$instance_count"); do
            systemctl "$action" "tippr-consumer-$consumer@$i"
        done
    done
done

