#!/usr/bin/env python3
"""
Wrap a command, setuid/setgid, change directory to the tippr
code, and send output to syslog.

The following environment variables may be used to control
the environment the wrapped command runs in:

TIPPR_USER

    The user to run the job as. Defaults to "tippr".

TIPPR_GROUP

    The group to run the job as. Defaults to $TIPPR_USER.

TIPPR_ROOT

    The root directory of the tippr package. It's where the makefile lives.

TIPPR_LOG_FACILITY

    The syslog facility to write messages to.
"""

import os
import sys
import grp
import pwd
import syslog
import subprocess


CONSUMER_PREFIX = "tippr-consumer-"


# drop permissions (only if running as root)
user = os.environ.get("TIPPR_USER", "tippr")
group = os.environ.get("TIPPR_GROUP", user)

if os.getuid() == 0:
    uid = pwd.getpwnam(user).pw_uid
    gid = grp.getgrnam(group).gr_gid
    os.setgroups([])
    os.setgid(gid)
    os.setuid(uid)

# change directory to the tippr code root
root = os.environ.get("TIPPR_ROOT", "/home/tippr/src/tippr/r2")
os.chdir(root)

# configure syslog - use SYSTEMD_UNIT if available, fall back to command args
job_name = os.environ.get("SYSTEMD_UNIT", os.environ.get("INVOCATION_ID", "-".join(sys.argv[1:])))
if job_name.startswith(CONSUMER_PREFIX):
    # consumers are a bit different from crons, while crons want an
    # ident of tippr-job-JOBNAME, we want consumers to have an ident
    # of CONSUMERNAME_INSTANCE
    job_name = job_name[len(CONSUMER_PREFIX):]

facility = getattr(syslog, "LOG_" + os.environ.get("TIPPR_LOG_FACILITY", "CRON"))
syslog.openlog(ident=job_name, facility=facility)

# run the wrapped command
child = subprocess.Popen(sys.argv[1:],
                         stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT,
                         bufsize=1,
                         text=True)

# write out to syslog
while True:
    line = child.stdout.readline()

    if not line:
        break

    line = line.rstrip('\n')
    syslog.syslog(syslog.LOG_NOTICE, line)
    print(line)

# our success depends on our child's success
child.wait()
sys.exit(child.returncode)
